name: technican
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.0.0

  # Firebase dependencies
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0
  geolocator: ^12.0.0
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  firebase_app_check: ^0.2.2+7
  image_picker: ^1.1.2
  cloudinary_public: ^0.23.1
  intl: ^0.20.2
  flutter_localization: ^0.2.1
  google_maps_flutter: ^2.12.3
  flutter_rating_bar: ^4.0.1
  webview_flutter: ^4.2.2
  connectivity_plus: ^6.1.4
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# ✅ خلى الإعدادات هنا (خارج قسم flutter:)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"
