// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChAqXcMV5ZxD9WDPluuw71TCNVbqATq9I',
    appId: '1:1038345833027:web:631065b39fbdfee9be22f6',
    messagingSenderId: '1038345833027',
    projectId: 'sal7ly-app-3a845',
    authDomain: 'sal7ly-app-3a845.firebaseapp.com',
    databaseURL: 'https://sal7ly-app-3a845-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sal7ly-app-3a845.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZHlDQBDRtQmEfu0Lrt_JJT8UV5QIYrZc',
    appId: '1:1038345833027:android:a0dd91b612b048c0be22f6',
    messagingSenderId: '1038345833027',
    projectId: 'sal7ly-app-3a845',
    databaseURL: 'https://sal7ly-app-3a845-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sal7ly-app-3a845.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ7j13x2hGOJc1FLqHxZF3Y-tvrSJ9tMI',
    appId: '1:1038345833027:ios:82e8e4a3e79c608cbe22f6',
    messagingSenderId: '1038345833027',
    projectId: 'sal7ly-app-3a845',
    databaseURL: 'https://sal7ly-app-3a845-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sal7ly-app-3a845.firebasestorage.app',
    iosBundleId: 'com.example.technican',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ7j13x2hGOJc1FLqHxZF3Y-tvrSJ9tMI',
    appId: '1:1038345833027:ios:82e8e4a3e79c608cbe22f6',
    messagingSenderId: '1038345833027',
    projectId: 'sal7ly-app-3a845',
    databaseURL: 'https://sal7ly-app-3a845-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sal7ly-app-3a845.firebasestorage.app',
    iosBundleId: 'com.example.technican',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChAqXcMV5ZxD9WDPluuw71TCNVbqATq9I',
    appId: '1:1038345833027:web:8d10c9afaab59e76be22f6',
    messagingSenderId: '1038345833027',
    projectId: 'sal7ly-app-3a845',
    authDomain: 'sal7ly-app-3a845.firebaseapp.com',
    databaseURL: 'https://sal7ly-app-3a845-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sal7ly-app-3a845.firebasestorage.app',
  );
}
